@echo off

rem 全てのリソースファイルを確認

echo check files... data\PC98\BG
if not exist PC98\BG\BG_01.MIG goto err
if not exist PC98\BG\BG_02.MIG goto err
if not exist PC98\BG\BG_02ITA.MIG goto err
if not exist PC98\BG\BG_03.MIG goto err
if not exist PC98\BG\BG_04.MIG goto err
if not exist PC98\BG\BG_05.MIG goto err
if not exist PC98\BG\BG_06.MIG goto err
if not exist PC98\BG\BG_07.MIG goto err
if not exist PC98\BG\BG_08.MIG goto err
if not exist PC98\BG\BG_09.MIG goto err
if not exist PC98\BG\BG_10.MIG goto err
if not exist PC98\BG\BG_11.MIG goto err
if not exist PC98\BG\BG_12.MIG goto err
if not exist PC98\BG\BG_13.MIG goto err
if not exist PC98\BG\BG_14.MIG goto err
if not exist PC98\BG\BG_15.MIG goto err
if not exist PC98\BG\BG_16.MIG goto err
if not exist PC98\BG\BG_17.MIG goto err
if not exist PC98\BG\BG_18.MIG goto err
if not exist PC98\BG\BG_19.MIG goto err
if not exist PC98\BG\BG_19_A.MIG goto err
if not exist PC98\BG\BG_20.MIG goto err
if not exist PC98\BG\BG_20_A.MIG goto err
if not exist PC98\BG\BG_21.MIG goto err
if not exist PC98\BG\BG_22.MIG goto err
if not exist PC98\BG\BG_23.MIG goto err
if not exist PC98\BG\BG_24.MIG goto err
if not exist PC98\BG\BG_25.MIG goto err
if not exist PC98\BG\BG_26.MIG goto err
if not exist PC98\BG\BG_27.MIG goto err
if not exist PC98\BG\BG_27A.MIG goto err
if not exist PC98\BG\BG_28.MIG goto err
if not exist PC98\BG\BG_28_A.MIG goto err
if not exist PC98\BG\BG_29.MIG goto err
if not exist PC98\BG\BG_30.MIG goto err
if not exist PC98\BG\BG_31.MIG goto err
if not exist PC98\BG\BG_32.MIG goto err
if not exist PC98\BG\BG_33.MIG goto err
if not exist PC98\BG\BG_34.MIG goto err
if not exist PC98\BG\BG_34A.MIG goto err
if not exist PC98\BG\BG_35.MIG goto err
if not exist PC98\BG\BG_36.MIG goto err
if not exist PC98\BG\BG_37.MIG goto err
if not exist PC98\BG\YBG_02IT.MIG goto err
if not exist PC98\BG\YBG_03.MIG goto err
if not exist PC98\BG\YBG_04.MIG goto err
if not exist PC98\BG\YBG_06.MIG goto err
if not exist PC98\BG\YBG_08.MIG goto err
if not exist PC98\BG\YBG_09.MIG goto err
if not exist PC98\BG\YBG_11.MIG goto err
if not exist PC98\BG\YBG_12.MIG goto err
if not exist PC98\BG\YBG_12A.MIG goto err
if not exist PC98\BG\YBG_13.MIG goto err
if not exist PC98\BG\YBG_14.MIG goto err
if not exist PC98\BG\YBG_16.MIG goto err
if not exist PC98\BG\YBG_17.MIG goto err
if not exist PC98\BG\YBG_19.MIG goto err
if not exist PC98\BG\YBG_20.MIG goto err
if not exist PC98\BG\YBG_21.MIG goto err
if not exist PC98\BG\YBG_24.MIG goto err
if not exist PC98\BG\YBG_25.MIG goto err
if not exist PC98\BG\YBG_29.MIG goto err
if not exist PC98\BG\YBG_33.MIG goto err
if not exist PC98\BG\YBG_34.MIG goto err

echo check files... data\PC98\BGM
if not exist PC98\BGM\A1A.M goto err
if not exist PC98\BGM\A2.M goto err
if not exist PC98\BGM\AME.M goto err
if not exist PC98\BGM\B1A.M goto err
if not exist PC98\BGM\B2.M goto err
if not exist PC98\BGM\C1.M goto err
if not exist PC98\BGM\C2.M goto err
if not exist PC98\BGM\D1A.M goto err
if not exist PC98\BGM\D2C.M goto err
if not exist PC98\BGM\E1B.M goto err
if not exist PC98\BGM\E2.M goto err
if not exist PC98\BGM\F1A.M goto err
if not exist PC98\BGM\G1.M goto err
if not exist PC98\BGM\G2A.M goto err
if not exist PC98\BGM\GAAN.M goto err
if not exist PC98\BGM\H1.M goto err
if not exist PC98\BGM\H2.M goto err
if not exist PC98\BGM\I1.M goto err
if not exist PC98\BGM\I2A.M goto err
if not exist PC98\BGM\JIRIRI.M goto err
if not exist PC98\BGM\KUTI2.M goto err
if not exist PC98\BGM\KUTIBUE.M goto err
if not exist PC98\BGM\M0059.M goto err
if not exist PC98\BGM\M78.M goto err
if not exist PC98\BGM\M78_2.M goto err
if not exist PC98\BGM\MAJAN.M goto err
if not exist PC98\BGM\MAJAN2.M goto err
if not exist PC98\BGM\MIZU.M goto err
if not exist PC98\BGM\NOIZE.M goto err
if not exist PC98\BGM\SHEYA.M goto err
if not exist PC98\BGM\SOUND.EFC goto err
if not exist PC98\BGM\SUZUME.M goto err
if not exist PC98\BGM\TOKEI.M goto err
if not exist PC98\BGM\TOKEI2.M goto err
if not exist PC98\BGM\UMI.M goto err
if not exist PC98\BGM\ZATTOU.M goto err

echo check files... data\PC98\CHR
if not exist PC98\CHR\AIHA_00.MIG goto err
if not exist PC98\CHR\AIHA_01.MIG goto err
if not exist PC98\CHR\AIHA_02.MIG goto err
if not exist PC98\CHR\AIHA_03.MIG goto err
if not exist PC98\CHR\ARI_00.MIG goto err
if not exist PC98\CHR\ASA_00.MIG goto err
if not exist PC98\CHR\ASA_01.MIG goto err
if not exist PC98\CHR\ASA_02.MIG goto err
if not exist PC98\CHR\ASA_03.MIG goto err
if not exist PC98\CHR\ASA_04.MIG goto err
if not exist PC98\CHR\ASA_05.MIG goto err
if not exist PC98\CHR\ASA_06.MIG goto err
if not exist PC98\CHR\ASA_07.MIG goto err
if not exist PC98\CHR\ASA_08.MIG goto err
if not exist PC98\CHR\CHUNE_00.MIG goto err
if not exist PC98\CHR\CHUNE_01.MIG goto err
if not exist PC98\CHR\CHUNE_02.MIG goto err
if not exist PC98\CHR\CHUNE_03.MIG goto err
if not exist PC98\CHR\CHUNE_A1.MIG goto err
if not exist PC98\CHR\CHUNE_A2.MIG goto err
if not exist PC98\CHR\HATA_00.MIG goto err
if not exist PC98\CHR\HAZU_00.MIG goto err
if not exist PC98\CHR\HAZU_01.MIG goto err
if not exist PC98\CHR\HAZU_02.MIG goto err
if not exist PC98\CHR\HAZU_03.MIG goto err
if not exist PC98\CHR\HAZU_04.MIG goto err
if not exist PC98\CHR\HAZU_05.MIG goto err
if not exist PC98\CHR\HAZU_06.MIG goto err
if not exist PC98\CHR\HIRO_00.MIG goto err
if not exist PC98\CHR\HIRO_01.MIG goto err
if not exist PC98\CHR\HIRO_02.MIG goto err
if not exist PC98\CHR\HIRO_03.MIG goto err
if not exist PC98\CHR\HIRO_04.MIG goto err
if not exist PC98\CHR\HIRO_05.MIG goto err
if not exist PC98\CHR\HIRO_06.MIG goto err
if not exist PC98\CHR\HIRO_07.MIG goto err
if not exist PC98\CHR\HIRO_08.MIG goto err
if not exist PC98\CHR\HIRO_09.MIG goto err
if not exist PC98\CHR\KYO_00.MIG goto err
if not exist PC98\CHR\KYO_01.MIG goto err
if not exist PC98\CHR\KYO_02.MIG goto err
if not exist PC98\CHR\KYO_03.MIG goto err
if not exist PC98\CHR\KYO_04.MIG goto err
if not exist PC98\CHR\OUME_00.MIG goto err
if not exist PC98\CHR\RISA_00.MIG goto err
if not exist PC98\CHR\RISA_01.MIG goto err
if not exist PC98\CHR\RISA_02.MIG goto err
if not exist PC98\CHR\RISA_03.MIG goto err
if not exist PC98\CHR\RISA_04.MIG goto err
if not exist PC98\CHR\RISA_05.MIG goto err
if not exist PC98\CHR\RISA_06.MIG goto err
if not exist PC98\CHR\RISA_07.MIG goto err
if not exist PC98\CHR\RISA_07A.MIG goto err
if not exist PC98\CHR\RISA_08.MIG goto err
if not exist PC98\CHR\RISA_08A.MIG goto err
if not exist PC98\CHR\RISA_08B.MIG goto err
if not exist PC98\CHR\RISA_08C.MIG goto err
if not exist PC98\CHR\RISA_09.MIG goto err
if not exist PC98\CHR\RISA_10.MIG goto err
if not exist PC98\CHR\RISA_11.MIG goto err
if not exist PC98\CHR\RISA_12.MIG goto err
if not exist PC98\CHR\RISA_13.MIG goto err
if not exist PC98\CHR\RISA_14.MIG goto err
if not exist PC98\CHR\SAKI_00.MIG goto err
if not exist PC98\CHR\SAKI_01.MIG goto err
if not exist PC98\CHR\SAKI_02.MIG goto err
if not exist PC98\CHR\SAKI_03.MIG goto err
if not exist PC98\CHR\SAKI_04.MIG goto err
if not exist PC98\CHR\SATO_00.MIG goto err
if not exist PC98\CHR\SATO_01.MIG goto err
if not exist PC98\CHR\SATO_02.MIG goto err
if not exist PC98\CHR\SATO_03.MIG goto err
if not exist PC98\CHR\SATO_04.MIG goto err
if not exist PC98\CHR\SEITO_00.MIG goto err
if not exist PC98\CHR\SUYA_00.MIG goto err
if not exist PC98\CHR\SUYA_01.MIG goto err
if not exist PC98\CHR\TOMO_00.MIG goto err
if not exist PC98\CHR\YUMI_00.MIG goto err
if not exist PC98\CHR\YUMI_02.MIG goto err
if not exist PC98\CHR\YUMI_03.MIG goto err
if not exist PC98\CHR\YUMI_04.MIG goto err
if not exist PC98\CHR\YUMI_05.MIG goto err
if not exist PC98\CHR\YUMI_06.MIG goto err
if not exist PC98\CHR\YUMI_07.MIG goto err

echo check files... data\PC98\ED
if not exist PC98\ED\ED_01A.MIG goto err
if not exist PC98\ED\ED_01B.MIG goto err
if not exist PC98\ED\ED_01C.MIG goto err
if not exist PC98\ED\ED_01D.MIG goto err
if not exist PC98\ED\ED_02A.MIG goto err
if not exist PC98\ED\ED_02B.MIG goto err
if not exist PC98\ED\ED_02C.MIG goto err
if not exist PC98\ED\ED_03A.MIG goto err
if not exist PC98\ED\ED_03A_2.MIG goto err
if not exist PC98\ED\ED_03B.MIG goto err
if not exist PC98\ED\ED_03C.MIG goto err
if not exist PC98\ED\ED_03D.MIG goto err
if not exist PC98\ED\ED_03E.MIG goto err
if not exist PC98\ED\ED_03F.MIG goto err
if not exist PC98\ED\ED_03G.MIG goto err
if not exist PC98\ED\ED_03H.MIG goto err
if not exist PC98\ED\ED_05.MIG goto err
if not exist PC98\ED\ED_06.MIG goto err
if not exist PC98\ED\ED_07.MIG goto err
if not exist PC98\ED\ED_08A.MIG goto err
if not exist PC98\ED\ED_08B.MIG goto err
if not exist PC98\ED\ED_09A.MIG goto err
if not exist PC98\ED\ED_09B.MIG goto err
if not exist PC98\ED\ED_10.MIG goto err
if not exist PC98\ED\ED_11.MIG goto err
if not exist PC98\ED\ED_12.MIG goto err
if not exist PC98\ED\ED_13.MIG goto err
if not exist PC98\ED\ED_14.MIG goto err
if not exist PC98\ED\ED_15.MIG goto err
if not exist PC98\ED\ED_16.MIG goto err
if not exist PC98\ED\ED_17.MIG goto err
if not exist PC98\ED\ED_18.MIG goto err

echo check files... data\PC98\ETC
if not exist PC98\ETC\BAD_END.MIG goto err
if not exist PC98\ETC\END.MIG goto err
if not exist PC98\ETC\LOGO.MIG goto err
if not exist PC98\ETC\MENUCG.MIG goto err
if not exist PC98\ETC\MENULOGO.MIG goto err
if not exist PC98\ETC\MENUMAIN.MIG goto err
if not exist PC98\ETC\MENUMUS.MIG goto err
if not exist PC98\ETC\NAME.MIG goto err
if not exist PC98\ETC\TXTFRAME.MIG goto err
if not exist PC98\ETC\WIN00.MIG goto err
if not exist PC98\ETC\WINCG.MIG goto err

echo check files... data\PC98\EV
if not exist PC98\EV\ETC_01A.MIG goto err
if not exist PC98\EV\ETC_01B.MIG goto err
if not exist PC98\EV\ETC_02.MIG goto err
if not exist PC98\EV\ETC_03.MIG goto err
if not exist PC98\EV\ETC_03A.MIG goto err
if not exist PC98\EV\ETC_04.MIG goto err
if not exist PC98\EV\ETC_05.MIG goto err
if not exist PC98\EV\ETC_06.MIG goto err
if not exist PC98\EV\ETC_08.MIG goto err
if not exist PC98\EV\E_01.MIG goto err
if not exist PC98\EV\E_02A.MIG goto err
if not exist PC98\EV\E_02B.MIG goto err
if not exist PC98\EV\E_02BG.MIG goto err
if not exist PC98\EV\E_02C.MIG goto err
if not exist PC98\EV\E_02D.MIG goto err
if not exist PC98\EV\E_03A.MIG goto err
if not exist PC98\EV\E_03B.MIG goto err
if not exist PC98\EV\E_04.MIG goto err
if not exist PC98\EV\E_05.MIG goto err
if not exist PC98\EV\E_06.MIG goto err
if not exist PC98\EV\E_07.MIG goto err
if not exist PC98\EV\E_08A.MIG goto err
if not exist PC98\EV\E_08B.MIG goto err
if not exist PC98\EV\E_09.MIG goto err
if not exist PC98\EV\E_10A.MIG goto err
if not exist PC98\EV\E_10BG.MIG goto err
if not exist PC98\EV\E_10C.MIG goto err
if not exist PC98\EV\E_11.MIG goto err
if not exist PC98\EV\E_12.MIG goto err
if not exist PC98\EV\E_13.MIG goto err
if not exist PC98\EV\E_14A.MIG goto err
if not exist PC98\EV\E_14B.MIG goto err
if not exist PC98\EV\E_15A.IDX goto err
if not exist PC98\EV\E_15A.MIG goto err
if not exist PC98\EV\E_15A.PIX goto err
if not exist PC98\EV\E_15B.IDX goto err
if not exist PC98\EV\E_15B.MIG goto err
if not exist PC98\EV\E_15B.PIX goto err
if not exist PC98\EV\E_15C.MIG goto err
if not exist PC98\EV\E_16.MIG goto err
if not exist PC98\EV\E_17A.MIG goto err
if not exist PC98\EV\E_17B.MIG goto err
if not exist PC98\EV\E_17C.MIG goto err
if not exist PC98\EV\E_17D.MIG goto err
if not exist PC98\EV\E_18A.MIG goto err
if not exist PC98\EV\E_18B.MIG goto err
if not exist PC98\EV\E_19.MIG goto err
if not exist PC98\EV\E_20.MIG goto err
if not exist PC98\EV\E_21.MIG goto err
if not exist PC98\EV\E_22.MIG goto err
if not exist PC98\EV\E_23.MIG goto err
if not exist PC98\EV\E_25A.MIG goto err
if not exist PC98\EV\E_25B.MIG goto err
if not exist PC98\EV\E_25C.MIG goto err
if not exist PC98\EV\E_25D.MIG goto err
if not exist PC98\EV\E_25E.MIG goto err
if not exist PC98\EV\E_25F.MIG goto err
if not exist PC98\EV\E_26.MIG goto err
if not exist PC98\EV\E_27A.MIG goto err
if not exist PC98\EV\E_27B.MIG goto err
if not exist PC98\EV\E_28.MIG goto err
if not exist PC98\EV\E_29A.MIG goto err
if not exist PC98\EV\E_29B.MIG goto err
if not exist PC98\EV\E_30A.MIG goto err
if not exist PC98\EV\E_30B.MIG goto err
if not exist PC98\EV\E_31.MIG goto err
if not exist PC98\EV\E_32.MIG goto err
if not exist PC98\EV\E_33.MIG goto err
if not exist PC98\EV\E_34.MIG goto err
if not exist PC98\EV\E_35A.MIG goto err
if not exist PC98\EV\E_35B.MIG goto err
if not exist PC98\EV\E_35C.MIG goto err
if not exist PC98\EV\E_36A.MIG goto err
if not exist PC98\EV\E_36B.MIG goto err
if not exist PC98\EV\E_36C.MIG goto err
if not exist PC98\EV\E_36D.MIG goto err
if not exist PC98\EV\E_37.MIG goto err
if not exist PC98\EV\E_38.MIG goto err
if not exist PC98\EV\E_39.MIG goto err
if not exist PC98\EV\E_40.MIG goto err
if not exist PC98\EV\E_41A.MIG goto err
if not exist PC98\EV\E_41B.MIG goto err
if not exist PC98\EV\E_42.MIG goto err
if not exist PC98\EV\E_43.MIG goto err
if not exist PC98\EV\E_44.MIG goto err
if not exist PC98\EV\E_45.MIG goto err
if not exist PC98\EV\E_46A.MIG goto err
if not exist PC98\EV\E_46B.MIG goto err
if not exist PC98\EV\E_46C.MIG goto err
if not exist PC98\EV\E_47A.MIG goto err
if not exist PC98\EV\E_47B.MIG goto err
if not exist PC98\EV\E_47BG.MIG goto err
if not exist PC98\EV\E_48A.MIG goto err
if not exist PC98\EV\E_48B.MIG goto err
if not exist PC98\EV\E_49A.MIG goto err
if not exist PC98\EV\E_49B.MIG goto err
if not exist PC98\EV\E_49C.IDX goto err
if not exist PC98\EV\E_49C.MIG goto err
if not exist PC98\EV\E_49C.PIX goto err
if not exist PC98\EV\E_49D.MIG goto err
if not exist PC98\EV\E_49E.MIG goto err
if not exist PC98\EV\E_50A.MIG goto err
if not exist PC98\EV\E_50B.MIG goto err
if not exist PC98\EV\E_51.MIG goto err
if not exist PC98\EV\E_52.MIG goto err
if not exist PC98\EV\E_53.MIG goto err
if not exist PC98\EV\E_54A.MIG goto err
if not exist PC98\EV\E_54B.MIG goto err
if not exist PC98\EV\E_55.MIG goto err
if not exist PC98\EV\E_56A.MIG goto err
if not exist PC98\EV\E_56B.MIG goto err
if not exist PC98\EV\E_56C.MIG goto err
if not exist PC98\EV\E_57A.MIG goto err
if not exist PC98\EV\E_57B.MIG goto err
if not exist PC98\EV\E_57C.MIG goto err
if not exist PC98\EV\E_58A.MIG goto err
if not exist PC98\EV\E_58B.MIG goto err
if not exist PC98\EV\E_59A.MIG goto err
if not exist PC98\EV\E_59B.MIG goto err

echo check files... data\PC98\H
if not exist PC98\H\H_01.MIG goto err
if not exist PC98\H\H_02A.MIG goto err
if not exist PC98\H\H_02B.MIG goto err
if not exist PC98\H\H_04.MIG goto err
if not exist PC98\H\H_05A.MIG goto err
if not exist PC98\H\H_05C.MIG goto err
if not exist PC98\H\H_05D.MIG goto err
if not exist PC98\H\H_05E.MIG goto err
if not exist PC98\H\H_06B.MIG goto err
if not exist PC98\H\H_07.MIG goto err
if not exist PC98\H\H_08.MIG goto err
if not exist PC98\H\H_09A.MIG goto err
if not exist PC98\H\H_09B.MIG goto err
if not exist PC98\H\H_09C.MIG goto err
if not exist PC98\H\H_09D.MIG goto err
if not exist PC98\H\H_10A.MIG goto err
if not exist PC98\H\H_10C.MIG goto err
if not exist PC98\H\H_11A.MIG goto err
if not exist PC98\H\H_11B.MIG goto err
if not exist PC98\H\H_11C.MIG goto err
if not exist PC98\H\H_12A.MIG goto err
if not exist PC98\H\H_12B.MIG goto err
if not exist PC98\H\H_12C.MIG goto err
if not exist PC98\H\H_12D.MIG goto err
if not exist PC98\H\H_12E.MIG goto err
if not exist PC98\H\H_12F.MIG goto err
if not exist PC98\H\H_12G.MIG goto err
if not exist PC98\H\H_13B.MIG goto err
if not exist PC98\H\H_13C.MIG goto err
if not exist PC98\H\H_14A.MIG goto err
if not exist PC98\H\H_14B.MIG goto err
if not exist PC98\H\H_14C.MIG goto err
if not exist PC98\H\H_15B.MIG goto err
if not exist PC98\H\H_15C.MIG goto err
if not exist PC98\H\H_15D.MIG goto err
if not exist PC98\H\H_16A.MIG goto err
if not exist PC98\H\H_16C.MIG goto err
if not exist PC98\H\H_18.MIG goto err
if not exist PC98\H\H_20B.MIG goto err
if not exist PC98\H\H_20C.MIG goto err
if not exist PC98\H\H_21A.MIG goto err
if not exist PC98\H\H_21C.MIG goto err
if not exist PC98\H\H_22A.MIG goto err
if not exist PC98\H\H_22B.MIG goto err
if not exist PC98\H\H_23A.MIG goto err
if not exist PC98\H\H_23B.MIG goto err
if not exist PC98\H\H_24.MIG goto err
if not exist PC98\H\H_25.MIG goto err
if not exist PC98\H\H_25A.MIG goto err
if not exist PC98\H\H_26A.MIG goto err
if not exist PC98\H\H_26C.MIG goto err
if not exist PC98\H\H_27A.MIG goto err
if not exist PC98\H\H_27C.MIG goto err
if not exist PC98\H\H_28A.MIG goto err
if not exist PC98\H\H_28B.MIG goto err
if not exist PC98\H\H_28C.MIG goto err
if not exist PC98\H\H_29A.MIG goto err
if not exist PC98\H\H_29B.MIG goto err
if not exist PC98\H\H_30A.MIG goto err
if not exist PC98\H\H_30B.MIG goto err
if not exist PC98\H\H_32A.MIG goto err
if not exist PC98\H\H_32B.MIG goto err
if not exist PC98\H\H_33.MIG goto err
if not exist PC98\H\H_34A.MIG goto err
if not exist PC98\H\H_34B.MIG goto err
if not exist PC98\H\H_35A.MIG goto err
if not exist PC98\H\H_35B.MIG goto err
if not exist PC98\H\H_35C.MIG goto err
if not exist PC98\H\H_36A.MIG goto err
if not exist PC98\H\H_36B.MIG goto err
if not exist PC98\H\H_37A.MIG goto err
if not exist PC98\H\H_37B.MIG goto err
if not exist PC98\H\H_39A.MIG goto err
if not exist PC98\H\H_40.MIG goto err

echo check files... data\PC98\OP
if not exist PC98\OP\MOJI01.MIG goto err
if not exist PC98\OP\OP_00.MIG goto err
if not exist PC98\OP\OP_01A.IDX goto err
if not exist PC98\OP\OP_01A.PIX goto err
if not exist PC98\OP\OP_01B.MIG goto err
if not exist PC98\OP\OP_02A.IDX goto err
if not exist PC98\OP\OP_02A.PIX goto err
if not exist PC98\OP\OP_03.MIG goto err
if not exist PC98\OP\OP_04.MIG goto err
if not exist PC98\OP\OP_05.MIG goto err
if not exist PC98\OP\OP_06.MIG goto err
if not exist PC98\OP\OP_07A.MIG goto err
if not exist PC98\OP\OP_07B.MIG goto err
if not exist PC98\OP\OP_07C.MIG goto err
if not exist PC98\OP\OP_07D.MIG goto err
if not exist PC98\OP\OP_07E.MIG goto err
if not exist PC98\OP\OP_07F.MIG goto err
if not exist PC98\OP\OP_08A.IDX goto err
if not exist PC98\OP\OP_08A.PIX goto err
if not exist PC98\OP\OP_08B.MIG goto err
if not exist PC98\OP\OP_09.MIG goto err
if not exist PC98\OP\ROOO.MIG goto err
if not exist PC98\OP\TAI_00.MIG goto err
if not exist PC98\OP\TAI_01.MIG goto err
if not exist PC98\OP\TAI_02.MIG goto err
if not exist PC98\OP\TAI_03.MIG goto err
if not exist PC98\OP\TAI_04.MIG goto err
if not exist PC98\OP\TAI_05.MIG goto err
if not exist PC98\OP\TAI_06.MIG goto err
if not exist PC98\OP\TAI_07.MIG goto err
if not exist PC98\OP\TAI_08.MIG goto err
if not exist PC98\OP\UMI.MIG goto err

echo check files... data\PC98
if not exist PC98\1DAY_A.SCP goto err
if not exist PC98\1DAY_B.SCP goto err
if not exist PC98\2DAY_A.SCP goto err
if not exist PC98\2DAY_B.SCP goto err
if not exist PC98\3DAY_A.SCP goto err
if not exist PC98\3DAY_B.SCP goto err
if not exist PC98\3DAY_C.SCP goto err
if not exist PC98\4BAD.SCP goto err
if not exist PC98\4DAY_A.SCP goto err
if not exist PC98\4DAY_B.SCP goto err
if not exist PC98\4DAY_C.SCP goto err
if not exist PC98\4DAY_D.SCP goto err
if not exist PC98\5BAD_A.SCP goto err
if not exist PC98\5BAD_B.SCP goto err
if not exist PC98\5BAD_C.SCP goto err
if not exist PC98\5BAD_D.SCP goto err
if not exist PC98\5DAY_A.SCP goto err
if not exist PC98\5DAY_B.SCP goto err
if not exist PC98\5DAY_C.SCP goto err
if not exist PC98\5DAY_D.SCP goto err
if not exist PC98\6DAY.SCP goto err
if not exist PC98\CG.SCP goto err
if not exist PC98\END.SCP goto err
if not exist PC98\IPL.SCP goto err
if not exist PC98\IPL2.SCP goto err
if not exist PC98\KABE.MIG goto err
if not exist PC98\MUSIC.SCP goto err
if not exist PC98\OPENING.SCP goto err
if not exist PC98\TAI.SCP goto err
if not exist PC98\WIN.MIG goto err


rem ---------------------------------
exit /b 0

rem ---------------------------------
:err
exit /b 1

